services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    ports:
      - 3030:3306
    volumes:
      - data:/var/lib/mysql

  wp:
    build:
      context: .
      dockerfile: ./build/wp.dockerfile
    container_name: wp
    restart: always
    links:
      - mariadb
    ports:
      - 8080:80
    env_file: .env
    volumes:
      - ./wordpress:/srv/wordpress
    command: bash -c "composer install && php-fpm"

volumes:
  data: