services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 3030:3306
    volumes:
      - data:/var/lib/mysql
  wp:
    build:
      context: .
      dockerfile: ./build/wp.dockerfile
    container_name: wp
    restart: always
    links:
      - mariadb
    depends_on:
      - mariadb
    ports:
      - 8080:80
      - 9001:9000
    env_file: .env
    volumes:
      - ./wordpress:/var/www/html/wordpress
  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - PMA_HOST=mariadb
    volumes:
      - ./phpmyadmin:/config
    ports:
      - 8181:80
    restart: unless-stopped
    links:
      - mariadb
    depends_on:
      - mariadb

volumes:
  data:
