name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md' # Avoid triggering the workflow due to non-essential changes

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Add Composer credentials conditionally
      - name: Add HTTP basic auth credentials
        run: |
          if [ ! -f wordpress/auth.json ]; then
            echo '${{ secrets.COMPOSER_AUTH_JSON }}' > wordpress/auth.json
          fi

      # Build and push Docker image with caching enabled
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: build/wp.dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          platforms: linux/amd64,linux/arm64
          build-args: |
            RUN_SUPERVISORD=false
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
